-- Características físicas opcionais dos perfis.
alter table public.perfis
  add column if not exists cor_olhos text,
  add column if not exists cor_pele text,
  add column if not exists cor_cabelo text;

-- Canal separado para suporte às modelos.
alter table public.config
  add column if not exists model_support_whatsapp text default '5511996425680';

update public.config
set model_support_whatsapp = '5511996425680'
where id = 1 and coalesce(model_support_whatsapp, '') = '';

-- Auditoria administrativa persistente.
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid,
  actor_email text,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  entity text not null,
  entity_id text,
  summary text,
  old_data jsonb,
  new_data jsonb
);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

alter table public.audit_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'audit_logs'
      and policyname = 'Authenticated users can read audit logs'
  ) then
    create policy "Authenticated users can read audit logs"
      on public.audit_logs for select
      to authenticated
      using (true);
  end if;
end $$;

create or replace function public.capture_admin_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  source_row jsonb;
  row_id text;
  row_summary text;
  user_email text;
begin
  source_row := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  row_id := coalesce(source_row->>'id', source_row->>'slug', '1');
  row_summary := coalesce(source_row->>'nome', source_row->>'titulo', source_row->>'slug', tg_table_name);
  select email into user_email from auth.users where id = auth.uid();

  insert into public.audit_logs (
    actor_id, actor_email, action, entity, entity_id, summary, old_data, new_data
  ) values (
    auth.uid(), user_email, tg_op, tg_table_name, row_id, row_summary,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) end
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['perfis', 'stories', 'cidades', 'config']
  loop
    execute format('drop trigger if exists audit_%I_changes on public.%I', table_name, table_name);
    execute format(
      'create trigger audit_%I_changes after insert or update or delete on public.%I for each row execute function public.capture_admin_audit_log()',
      table_name, table_name
    );
  end loop;
end $$;
