-- Server-side access auditing. IP addresses are personal data and are retained
-- for a limited period for security, fraud prevention, and incident response.

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('page_view', 'admin_page_view', 'admin_login_success')),
  path text not null,
  ip_address inet,
  user_agent text,
  referrer text,
  country_code text,
  admin_user_id uuid references auth.users(id) on delete set null,
  admin_email text,
  dedupe_key text unique
);

create index if not exists access_logs_created_at_idx on public.access_logs (created_at desc);
create index if not exists access_logs_ip_address_idx on public.access_logs (ip_address);
create index if not exists access_logs_event_type_idx on public.access_logs (event_type, created_at desc);

alter table public.access_logs enable row level security;
revoke all on public.access_logs from anon;
revoke insert, update, delete, truncate on public.access_logs from authenticated;
grant select on public.access_logs to authenticated;

drop policy if exists access_logs_admin_read on public.access_logs;
create policy access_logs_admin_read
  on public.access_logs
  for select
  to authenticated
  using ((select security.is_admin()));

-- Run periodically from Supabase Cron if available. It is deliberately not
-- exposed to browser roles.
create or replace function security.delete_expired_access_logs()
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  deleted_count bigint;
begin
  delete from public.access_logs where created_at < now() - interval '90 days';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function security.delete_expired_access_logs() from public, anon, authenticated;

-- Browser clients may request an access record, but the function derives the
-- IP and device metadata from trusted gateway headers. Callers cannot provide
-- or overwrite those values.
create or replace function public.record_access_event(p_event_type text, p_path text)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, security, auth
as $$
declare
  request_headers jsonb := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
  safe_event text;
  safe_path text;
  raw_ip text;
  parsed_ip inet;
  current_user_id uuid := auth.uid();
  current_email text;
  unique_key text;
begin
  safe_path := left(case when coalesce(p_path, '') like '/%' then split_part(p_path, '?', 1) else '/' end, 500);
  safe_event := case
    when p_event_type = 'admin_login_success' then 'admin_login_success'
    when safe_path like '/admin%' then 'admin_page_view'
    else 'page_view'
  end;

  if safe_event = 'admin_login_success' and not security.is_admin() then
    raise exception 'Admin authentication required' using errcode = '42501';
  end if;

  raw_ip := coalesce(
    request_headers->>'cf-connecting-ip',
    split_part(request_headers->>'x-forwarded-for', ',', 1)
  );
  begin
    parsed_ip := nullif(trim(raw_ip), '')::inet;
  exception when invalid_text_representation then
    parsed_ip := null;
  end;

  if safe_event = 'admin_login_success' then
    select email into current_email from auth.users where id = current_user_id;
  end if;

  unique_key := md5(concat_ws('|', safe_event, coalesce(parsed_ip::text, 'unknown'), safe_path,
    coalesce(current_user_id::text, ''), date_trunc('minute', now())::text));

  insert into public.access_logs (
    event_type, path, ip_address, user_agent, referrer, country_code,
    admin_user_id, admin_email, dedupe_key
  ) values (
    safe_event,
    safe_path,
    parsed_ip,
    left(request_headers->>'user-agent', 1000),
    left(coalesce(request_headers->>'referer', request_headers->>'referrer'), 1000),
    left(coalesce(request_headers->>'cf-ipcountry', request_headers->>'x-country-code'), 2),
    case when safe_event = 'admin_login_success' then current_user_id end,
    current_email,
    unique_key
  )
  on conflict (dedupe_key) do nothing;
end;
$$;

revoke all on function public.record_access_event(text, text) from public;
grant execute on function public.record_access_event(text, text) to anon, authenticated;
